# Generated by Django 4.1 on 2023-12-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='date_of_applying',
            field=models.DateField(auto_now=True),
        ),
    ]
