# Generated by Django 4.1 on 2024-02-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='age',
            field=models.IntegerField(default=14),
        ),
    ]
