# Generated by Django 4.2.8 on 2023-12-20 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("musician", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musician",
            name="age",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(21)]
            ),
        ),
    ]
