# Generated by Django 4.1 on 2023-11-29 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musician',
            old_name='data_of_applying',
            new_name='date_of_applying',
        ),
    ]
