# Generated by Django 4.1 on 2023-04-09 18:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("musician", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="musician",
            old_name="date_if_applying",
            new_name="date_of_applying",
        ),
    ]
