# Generated by Django 4.1 on 2024-01-08 09:53

from django.db import migrations, models
import musician.models


class Migration(migrations.Migration):
    dependencies = [
        ("musician", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musician",
            name="age",
            field=models.IntegerField(validators=[musician.models.validate_age]),
        ),
        migrations.AlterField(
            model_name="musician",
            name="date_of_applying",
            field=models.DateField(auto_now_add=True),
        ),
    ]
