# Generated by Django 4.1 on 2023-08-24 15:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("musician", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="musician",
            options={},
        ),
    ]
