# Generated by Django 4.1 on 2022-12-02 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musician", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="musician",
            name="age",
            field=models.IntegerField(
                default=14,
                validators=[
                    django.core.validators.MinValueValidator(
                        14, "Age must be over 14 years old "
                    )
                ],
            ),
            preserve_default=False,
        ),
    ]
