# Generated by Django 4.1 on 2023-03-09 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musician',
            old_name='instrument_name',
            new_name='instrument',
        ),
    ]
