# Generated by Django 4.1 on 2023-12-01 23:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("musician", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="musician",
            options={"ordering": ("age",)},
        ),
    ]
