# Generated by Django 4.1 on 2023-12-23 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0002_alter_musician_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(21)]),
        ),
    ]
